# Generated by Django 4.2.2 on 2023-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('mental health', 'Mental Health'), ('heart disease', 'Heart Disease'), ('covid19', 'Covid 19'), ('immunization', 'Immunization')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
